#include <random>
#include <iostream>
 
int main()
{
  /*std::random_device rd;  //Will be used to obtain a seed for the random number engine. este nos da una semilla aleatoria para que cada vez que corremos el programa, tal que cada una de estas veces tenemos numeros aleatorios diferentes */
  const int NSAMPLES = 10000;
  int seed = 1; 

  
    std::mt19937 gen(seed); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(0.0, 1.0);
    for (int n = 0; n < NSAMPLES; ++n) { // numero de numeros aleatorios
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
        std::cout << dis(gen) << ' ';
    }
    std::cout << '\n';
}
